name: Mr Little Bricks Build + FTP

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout Files
      uses: actions/checkout@v4

    - name: ByteToast-Studio Client 
      working-directory: ./client
      run: npm ci

    - name: ByteToast-Studio Client Build 
      run: npm run build --if-present
      working-directory: ./client
      env:
        CI: false
